### ISSUE TITLE
Vonage Grafana_Status_panel version out of date in repo

### ISSUE THREAD

**Issue by danatinflux** [grafana/grafana-plugin-repository#1037]
This is currently in the file (https://github.com/grafana/grafana-plugin-repository/blob/master/repo.json) :

```
      "id": "vonage-status-panel",
      "type": "panel",
      "url": "https://github.com/Vonage/Grafana_Status_panel",
      "versions": [
        {
          "version": "1.0.10",
          "commit": "ca77e0dd94b27088f071f8d61a67fe0256faca2f",
          "url": "https://github.com/Vonage/Grafana_Status_panel"
        },
```

However, on the web page it's 1.0.11:

https://grafana.com/grafana/plugins/vonage-status-panel/

![image](https://user-images.githubusercontent.com/44617130/129406004-e1301cd3-e9d4-4c7c-a0c2-3701bd15c625.png)

This is preventing users from using it, as the 1.0.10 is not properly signed, apparently. 

Thanks!

**Comment by ebezdomnikov** [comment]
Any update regards this issue?

**Comment by marcusolsson** [comment]
Responded in the mentioned issue. Closing this one.
