### ISSUE TITLE
"A plugin with the specified slug already exists" show up when I submit my plugin

### ISSUE THREAD

**Issue by sangshuduo** [grafana/grafana-plugin-repository#1053]
hi there,

I am trying to submit a data source (time-series database TDengine) plugin to Grafana with the new process. When I click the submit button, a msg shows up at the bottom "A plugin with the specified slug already exists" few seconds then disappeared. I did submit the plugin (https://github.com/grafana/grafana-plugin-repository/pull/704) at an early time but it did not pass validation successfully. I don't if the error msg is related to my early submission. I wonder how to solve it now. Appreciated it if someone can help.

Shuduo | TAOS Data

**Comment by KatrinaTurner** [comment]
This just happened to me as well trying to submit a plugin I had previously submitted the legacy way with a pull request here.

**Comment by sangshuduo** [comment]
> 
> 
> This just happened to me as well trying to submit a plugin I had previously submitted the legacy way with a pull request here.

thanks. already use the new way to submit.
