### ISSUE TITLE
Cannot submit an update for an already published plugin

### ISSUE THREAD

**Issue by ofir5300** [grafana/grafana-plugin-repository#1054]
Hello, 
I am the maintainer of **_bigquery-grafana plugin by DoiT International_**.
I am willing to submit a [version 2.0.3 update](https://github.com/doitintl/bigquery-grafana/releases/tag/2.0.3) for our plugin.
When I am trying to use the new submission method described on your README im running into an error.
1. You did not explain how should I configure grafana cloud to recognise me as a part of a team which already has a live plugin, so it will appear on `Published Plugins` section and will allow me to `update plugin`
2. When im trying to use `submit plugin` im getting this error:
```Plugin id contains incorrect org. Expected: ofircohen, but got: doitintl.```

How should I act?
@daniellee @marcusolsson

**Comment by marcusolsson** [comment]
Hi!

You need to be invited to the `dointl` team by one of the admins. When you've been added to the team, you can select the active org from a drop-down the top-left corner of My Account. After you've switched to doitintl, you should be able to submit it.
