### ISSUE TITLE
Subproject or project URL

### ISSUE THREAD

**Issue by ambud** [grafana/grafana-plugin-repository#144]
Is it possible to use a subproject github URL for the plugin or does it need to be a full project URL i.e. will this work? https://github.com/srotya/sidewinder/tree/development/grafana

**Comment by daniellee** [comment]
Not entirely sure. It might work. If it does not work then we can change our publishing code to handle this case.

**Comment by DanCech** [comment]
It doesn't work because github doesn't provide any capability to generate a zipball of a subfolder.

**Comment by ambud** [comment]
Created a pull request using a brand new repository: https://github.com/grafana/grafana-plugin-repository/pull/146
