### ISSUE TITLE
Worst docs and tutorials for plug in dev

### ISSUE THREAD

**Issue by joehoeller** [grafana/grafana-plugin-repository#153]
Id like to work with you to develop a solid tut on plug in dev.

**Comment by daniellee** [comment]
That would be great. We are a small team (currently 2 people) that take care of Grafana and the plugin ecosystem. Any help is much appreciated. 

You can find the docs for plugin dev in the Grafana repo:

https://github.com/grafana/grafana/tree/master/docs/sources/plugins/developing

**Comment by daniellee** [comment]
@joehoeller closing this as I didn't get a response. But if you are still interested in writing a tutorial or helping with the docs then please let me know.

**Comment by joehoeller** [comment]
Sorry I have been super busy and I just got to this, yes lets figure out a better tut for custom scripts
