### ISSUE TITLE
publication planified ?

### ISSUE THREAD

**Issue by algenty** [grafana/grafana-plugin-repository#493]
Hi grafana team,
I am the author Flowcharting plugin. 
I have increasingly issues on the project, maybe the number of users increases too (any stats on it ?).
To schedule releases, I need to know the frequency of publication.
Is there a rule? How can I help you in quality analysis? required deliverable ?

BR
Arnaud

**Comment by daniellee** [comment]
Hi @algenty,

There are 2363 installs of the Flowcharting plugin which is really good in such a short time. (We don't have a public Grafana dashboard for this yet.)

We are aiming to be much better at publishing plugin regularly - so not so much you need to do. It is us in the Grafana team who have to do better. Your plugin update should get published within a week or of you submitting it.
