### ISSUE TITLE
little question with toolkit

### ISSUE THREAD

**Issue by algenty** [grafana/grafana-plugin-repository#511]
Hi Grafana team,

A little question, with grafana-toolkit, should the dist directory be part of the delivery git or you build it ?

BR
Arnaud

**Comment by briangann** [comment]
we're creating a branch for a release, building inside there, and committing "dist" inside the release branch.

this lets us separate source code changes/PR's from the "generated" files in dist.

you can take a look at our circleci configurations also to duplicate the behavior easily.

Thanks!
