### ISSUE TITLE
Installed Plugins are not showing in dashboard

### ISSUE THREAD

**Issue by Supposethat4** [grafana/grafana-plugin-repository#552]
I have installed some plugins to use it for plotting data . These plugins are showing in plugin folder but not in dashboard while selecting visualization .  Please see attached images.
![Screenshot (72)](https://user-images.githubusercontent.com/59995665/72616779-6fdf5000-3959-11ea-87e7-26b57293df5f.png)
![Screenshot (71)](https://user-images.githubusercontent.com/59995665/72616780-7077e680-3959-11ea-9eb3-4bed7424f210.png)

**Comment by briangann** [comment]
Can you restart the grafana service and see if they are recognized once it starts back up?  (this may be a cli issue)

**Comment by Supposethat4** [comment]
@briangann Thanks issue has been resolved.
