### ISSUE TITLE
grafana.net doesn't update README.md from plugin repository

### ISSUE THREAD

**Issue by Slach** [grafana/grafana-plugin-repository#681]
https://grafana.com/grafana/plugins/vertamedia-clickhouse-datasource
contains README different than https://github.com/Vertamedia/clickhouse-grafana/blob/master/dist/README.md

**Comment by marcusolsson** [comment]
This seems to be the published README: https://github.com/Vertamedia/clickhouse-grafana/blob/bcee398e90e5f3ddb1140034c9f436b1b399a158/dist/README.md

Could you point me to where they are different?

**Comment by Slach** [comment]
sorry it was a mistake with my expectation, we can close issue
