### ISSUE TITLE
Empty pages on developer docs

### ISSUE THREAD

**Issue by faxm0dem** [grafana/grafana-plugin-repository#793]
I'm trying to follow the guide on how to publish a plugin.
But when clicking on few links, they are broken as they result in empty pages:

https://grafana.com/docs/grafana/latest/plugins/developing/plugin-review-guidelines/
https://grafana.com/docs/grafana/latest/plugins/developing/

Thanks !

**Comment by marcusolsson** [comment]
Thank you for reporting this, I've submitted a fix the the grafana repository!
