### ISSUE TITLE
Error with Zabbix plugin in Grafana

### ISSUE THREAD

**Issue by JeanDanielMbakob** [grafana/grafana-plugin-repository#883]
Uncaught (in promise) 
Object
config:
data: {datasourceId: 37, method: "apiinfo.version", params: {…}}
headers: {Content-Type: "application/json", X-Grafana-Org-Id: 1}
hideFromInspector: false
method: "POST"
retry: 0
url: "api/datasources/37/resources/zabbix-api"
__proto__: Object
data:
error: "Internal Server Error"
message: "Post "https://xxxxxxx/zabbix/api_jsonprc": context deadline exceeded"
__proto__: Object
**status: 500
statusText: "Internal Server Error"**
__proto__:
constructor: ƒ Object()
hasOwnProperty: ƒ hasOwnProperty()
isPrototypeOf: ƒ isPrototypeOf()
propertyIsEnumerable: ƒ propertyIsEnumerable()
toLocaleString: ƒ toLocaleString()
toString: ƒ toString()
valueOf: ƒ valueOf()
__defineGetter__: ƒ __defineGetter__()
__defineSetter__: ƒ __defineSetter__()
__lookupGetter__: ƒ __lookupGetter__()
__lookupSetter__: ƒ __lookupSetter__()
get __proto__: ƒ __proto__()
set __proto__: ƒ __proto__()

**Comment by marcusolsson** [comment]
Please submit any plugin related issues to the plugin's project page. 

https://github.com/alexanderzobnin/grafana-zabbix
