### ISSUE TITLE
Plugin auxmoney-waterfall-panel is not installable by grafana-cli

### ISSUE THREAD

**Issue by cawolf** [grafana/grafana-plugin-repository#994]
Hi,

we added a new panel plugin in #863 and installed it successfully in our production environment using the ZIP file provided at [grafana.com](https://grafana.com/grafana/plugins/auxmoney-waterfall-panel/?tab=installation). Now, an external user tried to install it by `grafana-cli` in his/her environment, but got the error ( see auxmoney/grafana-waterfall-panel#8 ):

    failed to find plugin 'auxmoney-waterfall-panel' in plugin repository. Please check if plugin ID is correct

I can reproduce this behaviour in a fresh grafana docker environment, and additionally, `grafana plugins list-remote` does not even show our plugin, which explains the error at install time.

What steps do we need to make in order to make our plugin available for `grafana-cli`? Did we misconfigure something?

Thanks in advance,
best regards,
@cawolf

**Comment by shidaying** [comment]
yeah, can install success by [grafana.com ](https://grafana.com/grafana/plugins/auxmoney-waterfall-panel/?tab=installation)
but can not install success by grafana-cli or by ```git clone https://github.com/auxmoney/grafana-waterfall-panel.git ```

**Comment by marcusolsson** [comment]
Hi @cawolf and @shidaying,

I'm able to install the plugin when using 7.5.7 but not on 8.0. Could you confirm that is the case for you as well?

The plugin has defined the `grafanaDependency` as `7.x.x`, which means that it won't be discoverable by anyone using 8.0.

@cawolf If you'd like to extend support for 8.0, I recommend setting `grafanaDependency` to something like `>=7.0`, or `7.x | 8.x`, and publishing a new version.

**Comment by cawolf** [comment]
Hi @marcusolsson ,

thank you for pointing us in the right direction. I was aware of Grafana 8 being released, but didn't make the connection. I will fix this with a version union and create a new version and PR to update your plugin repository as well.

**Comment by marcusolsson** [comment]
Looking forward to it! We'll be improving the error message to make this a little clearer.

**Comment by marcusolsson** [comment]
Improved error message: https://github.com/grafana/grafana/pull/36556
